-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
      -   id: detect-aws-credentials
      -   id: trailing-whitespace
      -   id: check-yaml
-   repo: git://github.com/kintoandar/pre-commit
    sha: v0.0.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
